# golangci-lint configuration for BreakBear
version: 2

run:
  timeout: 5m

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  disable-all: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0